version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
  aws-ecr: circleci/aws-ecr@6.7.0

executors:
  kubernetes-deployment:
    docker:
      - image: 815541116700.dkr.ecr.eu-central-1.amazonaws.com/kubernetes-deployment:v6
    working_directory: ~/repo

jobs:
  build:
    executor: kubernetes-deployment
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/install
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
      - aws-ecr/ecr-login
      - run:
          name: Build loggen
          command: docker build -t loggen:${CIRCLE_SHA1} .
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  deploy:
    executor: kubernetes-deployment
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-ecr/ecr-login

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master